[package]
name = "RSA"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
num = { version = "0.4", features = ["rand"] }
num-prime = { version = "0.4.2", features = ["num-bigint"] }
ascii_converter = "0.3.0"
num-bigint = "0.4.3"
glass_pumpkin = "1.5.0"
num-primes = "0.3.0"
bit-set = "0.5.3"
byte_array = "0.1.3"
chrono = "0.4.23"
bit-vec = "0.6.3"
bit_reverse = "0.1.8"
